### ISSUE TITLE
msfs200 freeze

### ISSUE THREAD

**Issue by cangianos** [mixMugz/msfs_tbm930_project#6] opened 2021-02-24 12:40 UTC
Using the last G3000 0.4.1 the msfs2020 freeze.   Back to 0.4.0 same freeze. Removing your mod the sim works.

https://github.com/Working-Title-MSFS-Mods/fspackages/issues/942

**Comment by WebMaximus** [comment] 2021-02-24 14:57
I don't have any issues over here using G3000 0.4.1 flying the TBM 930 with the aircraft-tbm930-improvement mod. I did however see how MSFS froze when trying to quit. Where I eventually had no other option than to terminate MSFS using Task Manager.

I think it's caused by the workingtitle-g3000-roaddata mod but more testing required to know for sure. So if you have that one installed, try removing it and see if you still have the same issue.

**Comment by WebMaximus** [comment] 2021-02-24 18:38
I can now confirm with certainty it's the workingtitle-g3000-roaddata mod that causes MSFS to freeze over here when trying to quit MSFS. I'll go ahead and report it in the proper place.

**Comment by Lysdestic** [comment] 2021-02-24 18:45
> I can now confirm with certainty it's the workingtitle-g3000-roaddata mod that causes MSFS to freeze over here when trying to quit MSFS. I'll go ahead and report it in the proper place.

For what it's worth, inside of the readme contained within the workingtotle-g3000-roaddata file, there is a list of known issues:

> ### Known Issues
- Road data is currently unavailable for Tajikistan.
- **MSFS will take an increased amount of time to fully shut down (up to several minutes) when closing the game after starting a flight that uses the road data in this package. The game window will still close promptly, but the game process will run in the background and game audio can be heard. The process is not frozen and will eventually shut down on its own, however if you wish to speed up the process, you can manually end-task or end-process MSFS through Task Manager.**

**Comment by WebMaximus** [comment] 2021-02-24 18:52
Ah, I should have RTFM 😊

**Comment by cangianos** [comment] 2021-03-04 09:41
Yeah, I finally found what mod is incompatible with G3000 and TBM. I forgot to remove the Navigraph beta mod. So if someone is getting freeze of FS2020, just remove the navigraph beta mod. ISSUE solved..

**Comment by WebMaximus** [comment] 2021-03-04 10:50
> Yeah, I finally found what mod is incompatible with G3000 and TBM. I forgot to remove the Navigraph beta mod. So if someone is getting freeze of FS2020, just remove the navigraph beta mod. ISSUE solved..

That's interesting! I have the latest Navigraph AIRAC (2102 Rev 2) installed together with the latest versions of both the G3000 and the TBM.

Can you be a bit more specific in what situations MSFS will freeze when you have the Navigraph AIRAC installed?

**Comment by cangianos** [comment] 2021-03-04 15:21
> > Yeah, I finally found what mod is incompatible with G3000 and TBM. I forgot to remove the Navigraph beta mod. So if someone is getting freeze of FS2020, just remove the navigraph beta mod. ISSUE solved..
> 
> That's interesting! I have the latest Navigraph AIRAC (2102 Rev 2) installed together with the latest versions of both the G3000 and the TBM.
> 
> Can you be a bit more specific in what situations MSFS will freeze when you have the Navigraph AIRAC installed?

If I load a new flight with the TBM with avionic already on, the SIm freeze. It remains stuck on the loading page of the flight. The loading page that should show you the airport. I can't start the fly and I have to quit FS2020. Removing the two navigraph folders from community root I solved the problem.

**Comment by WebMaximus** [comment] 2021-03-04 16:55
> > > Yeah, I finally found what mod is incompatible with G3000 and TBM. I forgot to remove the Navigraph beta mod. So if someone is getting freeze of FS2020, just remove the navigraph beta mod. ISSUE solved..
> > 
> > 
> > That's interesting! I have the latest Navigraph AIRAC (2102 Rev 2) installed together with the latest versions of both the G3000 and the TBM.
> > Can you be a bit more specific in what situations MSFS will freeze when you have the Navigraph AIRAC installed?
> 
> If I load a new flight with the TBM with avionic already on, the SIm freeze. It remains stuck on the loading page of the flight. The loading page that should show you the airport. I can't start the fly and I have to quit FS2020. Removing the two navigraph folders from community root I solved the problem.

OK, I guess I didn't try to load a flight plan with the avionics already ON. Maybe that's why I haven't seen this issue. One thing which puzzles me a bit is you saying you have two Navigraph folders in the Community folder. I only have one called navigraph-navdata.

**Comment by mixMugz** [comment] 2021-12-08 22:18
Issue still exist?

**Comment by cangianos** [comment] 2021-12-08 22:20
Hi, no.

No freeze now

Thanks



Il Mer 8 Dic 2021, 22:18 Maksim Brykov ***@***.***> ha
scritto:

**Closed** 2021-12-08 22:21 UTC
