### ISSUE TITLE
External model is incompete after SU8

### ISSUE THREAD

**Issue by umbepedro** [mixMugz/msfs_tbm930_project#46] opened 2022-03-05 14:23 UTC
Here what's happening after MSFS update 8. Default TBM works fine

![Microsoft Flight Simulator Screenshot 2022 03 05 - 14 41 40 74](https://user-images.githubusercontent.com/101004952/156887424-b0f93834-ce89-42ea-b6e3-4f5b5e14858c.png)

**Comment by WebMaximus** [comment] 2022-03-05 14:39
That have to be something local because I don't have that problem using the mod with SU8. Everything looks normal over here.

**Comment by WebMaximus** [comment] 2022-03-05 16:52
To add to what I said above, I just noticed I have this issue when in the MSFS main menu if I go to 'My hangar'. After loading a flight though, the aircraft looks fine.

This is how it looks in my hangar in MSFS
![TBM 930 mod skeleton](https://user-images.githubusercontent.com/40132448/156892592-25f377fc-0b12-4e3a-8a24-4485c92a1622.jpg)

**Comment by sinistre1973** [comment] 2022-03-05 19:12
When flying, the outside view is the same as above.

**Comment by WebMaximus** [comment] 2022-03-05 19:43
That's odd. But in my case, the aircraft looks good when flying.

**Comment by umbepedro** [comment] 2022-03-06 08:47
> That's odd. Because in my case, the aircraft looks good when flying.

I have the same problem in the hangar and while flying. 
The interior are fine but you cannot see wings and propeller.
Seems there is an incompability with the new update (it already happened with SU7). 

I hope @mixMugz  can fix it.

**Comment by WebMaximus** [comment] 2022-03-06 08:57
As mentioned previously, it can't be just the mod but needs to be something else as well. Since I don't have the issue when flying. If the mod was the sole culprit, we would all have the same issue when using the mod.

With this said, mixMugz might have an idea what could be causing this kind of issue.

**Comment by umbepedro** [comment] 2022-03-06 11:36
> As mentioned previously, it can't be just the mod but needs to be something else as well. Since I don't have the issue when flying. If the mod was the sole culprit, we would all have the same issue when using the mod.
> 
> With this said, mixMugz might have an idea what could be causing this kind of issue.

Just to be sure I removed everything in the community folder, the result is the same.
As you can see I'm not the only one with this issue. Let's say you are lucky :)

![aaaaa](https://user-images.githubusercontent.com/101004952/156921300-7d862873-fc4f-423c-be5d-0aa80d0c9e2f.PNG)

**Comment by WebMaximus** [comment] 2022-03-06 12:14
Guess I must be 🙂

I hope you guys having this issue will find a cure for it 👍

**Comment by sinistre1973** [comment] 2022-03-06 15:24
I deleted everything in the community folder and only left the TBM mod in there. Still incomplete! But then I changed the livery and the plane was normal again. It seems the problem is the default livery. All others are OK.

**Comment by WebMaximus** [comment] 2022-03-06 15:48
Well spotted and happy to hear you found the culprit 🙂

**Comment by mixMugz** [comment] 2022-03-07 19:36
Fixed in v0.6.4.0

**Closed by mixMugz** 2022-03-07 19:36 UTC
